/**
*___________________________________________________
*@Name: ContactStaticUtility
*@Author: Hemanth Kesapragada
*@Created: Date: 11/22/2017
*@Used_By: SPARTN
*___________________________________________________
*@Description: Generic Utility class for Contact triggers
*___________________________________________________
*@Changes: 
* MM-DD-YYY. Explanation of the change.
**/
public class ContactStaticUtility {
	public static string TriggerErrorMessage; 
}