/**
*___________________________________________________
*@Name: RevSys_ViolationExtension 
*@Author: Mona Bhutada
*@Created: Date: 01/29/2018
*@Used_By: SPARTN
*___________________________________________________
*@Description: Violation Extension for Review Systems Records 
* This class extends the Trigger Handler and invokes the Handler for further logic.
* Put the logic in a helper/utility class. 
*___________________________________________________
*@Changes: 
* MM-DD-YYY. Explanation of the change.
**/
public with sharing class RevSys_ViolationExtension {

    // This class will be removed     

     public static void deprecatedClass() {  

        Boolean checkMe = TRUE; 
     }
}