/**
*___________________________________________________
*@Name: Revsys_ViolationExtension_Test
*@Author: Walley
*@Created: Date: 4/13/2018
*@Used_By: SPARTN
*___________________________________________________
*@Description: Test class for Revsys_ViolationExtension class
*  This class will be deprecated
*___________________________________________________
*@Changes: 
* 
**/
@isTest
public class Revsys_ViolationExtension_Test {

    testmethod static void test_deprecatedClass(){

        Revsys_ViolationExtension.deprecatedClass(); 

    }
}